<a href="https://colab.research.google.com/github/MukRodrigues/Projetos-Python/blob/main/Calculo_Sistema.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [478]:
import numpy as mp
from numpy import *
from numpy.linalg import *

### Matrizes do Sistema

In [479]:
A = array([[0.1667, 0.0833, 0      , 0      , 0 ],
[0.0833 , 0.3334 , 0.0833 , 0      , 0 ],
[0      , 0.0833 , 0.3334 , 0.0833 , 0],
[0      , 0      , 0.0833 , 0.3334 , 0.0833],
[0      , 0      , 0      , 0.0833 , 0.1667 ]])

B = array([[2.333 , -1.833 , 0      , 0      , 0  ],
[-1.833 , 4.666 , -1.833 , 0      , 0  ],
[0      , -1.833 , 4.666 , -1.833 , 0],
[0      , 0      , -1.833 , 4.666 , -1.833],
[0      , 0      , 0      , -1.833 , 2.333 ]])

F = array([0.1259, 0.4489,0, -0.4484, -0.1257 ])

c0 = array([0, 0.101321, 0, -0.101321, 0])

k = 0.25

def soma_vet_forca(F,k,n):
  soma = (exp( (n+1)*k   ) + exp( (n)*k))   #F = F_{n+1} + F_{n}
  return F*soma

In [480]:
soma_vet_forca(F,k,0)

array([ 0.2875588 ,  1.02529901,  0.        , -1.024157  , -0.28710199])

Sistema

$$\left(A+ \frac{k}{2} B \right) c_{n+1} = \left(A- \frac{k}{2} B \right)c_{n} + \frac{k}{2}(F_{n+1} + F_{n} ) $$

In [481]:
k = 0.25
soma = A + k/2 * B
soma

array([[ 0.458325, -0.145825,  0.      ,  0.      ,  0.      ],
       [-0.145825,  0.91665 , -0.145825,  0.      ,  0.      ],
       [ 0.      , -0.145825,  0.91665 , -0.145825,  0.      ],
       [ 0.      ,  0.      , -0.145825,  0.91665 , -0.145825],
       [ 0.      ,  0.      ,  0.      , -0.145825,  0.458325]])

In [482]:
subt = A - k/2 * B
subt

array([[-0.124925,  0.312425,  0.      ,  0.      ,  0.      ],
       [ 0.312425, -0.24985 ,  0.312425,  0.      ,  0.      ],
       [ 0.      ,  0.312425, -0.24985 ,  0.312425,  0.      ],
       [ 0.      ,  0.      ,  0.312425, -0.24985 ,  0.312425],
       [ 0.      ,  0.      ,  0.      ,  0.312425, -0.124925]])

In [483]:
#lado direito da equação para n = 0
(dot(subt, c0) + k/2* soma_vet_forca(F,k,0)).round(4)

array([ 0.0676,  0.1028,  0.    , -0.1027, -0.0675])

In [484]:
#calculando c_1 a partir de c0
def sol_sistema(n):
  c = dot(dot(inv(soma), subt), c0) + k/2* dot(dot(inv(soma), subt), soma_vet_forca(F,k,n))
  return c

c1 = sol_sistema(0).round(3)
c1

array([ 0.138, -0.028,  0.   ,  0.028, -0.138])

In [485]:
#lado direito da equação para n = 1
(dot(subt, c1) + k/2* soma_vet_forca(F,k,1)).round(4)

array([ 0.0202,  0.2147,  0.    , -0.2145, -0.0201])

In [486]:
#calculando c_2 a partir de c1
def sol_sistema(n):
  c = dot(dot(inv(soma), subt), c1) + k/2* dot(dot(inv(soma), subt), soma_vet_forca(F,k,n))
  return c

c2 = sol_sistema(1).round(4)
c2

array([ 0.0537,  0.0341,  0.0001, -0.0341, -0.0536])

### Matriz Aumentada - Eliminação Gauss

#### n = 0

In [487]:
#lado direito da equação para n = 0
(dot(subt, c0) + k/2* soma_vet_forca(F,k,0)).round(4)

array([ 0.0676,  0.1028,  0.    , -0.1027, -0.0675])

In [488]:
#aumentada
A0 = array([[ 0.458325, -0.145825,  0.      ,  0.      ,  0.     , 0.0676 ],
       [-0.145825,  0.91665 , -0.145825,  0.      ,  0.    ,  0.1028   ],
       [ 0.      , -0.145825,  0.91665 , -0.145825,  0.     , 0.   ],
       [ 0.      ,  0.      , -0.145825,  0.91665 , -0.145825, -0.1027],
       [ 0.      ,  0.      ,  0.      , -0.145825,  0.458325, -0.0675 ]])

A0

array([[ 0.458325, -0.145825,  0.      ,  0.      ,  0.      ,  0.0676  ],
       [-0.145825,  0.91665 , -0.145825,  0.      ,  0.      ,  0.1028  ],
       [ 0.      , -0.145825,  0.91665 , -0.145825,  0.      ,  0.      ],
       [ 0.      ,  0.      , -0.145825,  0.91665 , -0.145825, -0.1027  ],
       [ 0.      ,  0.      ,  0.      , -0.145825,  0.458325, -0.0675  ]])

In [489]:
# L1 <- L1 / a11
A0[0:1] = A0[0:1] /  A0[0:1, 0]      #para acessar os elementos [linha:coluna, elemento]

A0

array([[ 1.        , -0.31816942,  0.        ,  0.        ,  0.        ,
         0.14749359],
       [-0.145825  ,  0.91665   , -0.145825  ,  0.        ,  0.        ,
         0.1028    ],
       [ 0.        , -0.145825  ,  0.91665   , -0.145825  ,  0.        ,
         0.        ],
       [ 0.        ,  0.        , -0.145825  ,  0.91665   , -0.145825  ,
        -0.1027    ],
       [ 0.        ,  0.        ,  0.        , -0.145825  ,  0.458325  ,
        -0.0675    ]])

In [490]:
# L2 <- L2 - a21* L1
A0[1:2] = A0[1:2] - A0[1:2, 0] *A0[0:1]
A0[1:2] = A0[1:2] / A0[1:2,1]
A0

array([[ 1.        , -0.31816942,  0.        ,  0.        ,  0.        ,
         0.14749359],
       [ 0.        ,  1.        , -0.16756622,  0.        ,  0.        ,
         0.14284152],
       [ 0.        , -0.145825  ,  0.91665   , -0.145825  ,  0.        ,
         0.        ],
       [ 0.        ,  0.        , -0.145825  ,  0.91665   , -0.145825  ,
        -0.1027    ],
       [ 0.        ,  0.        ,  0.        , -0.145825  ,  0.458325  ,
        -0.0675    ]])

In [491]:
# L3 <- L3 - a31* L1
A0[2:3] = A0[2:3] - A0[2:3, 0] *A0[0:1]

# L3 <- L3 - a32* L2
A0[2:3] = A0[2:3] - A0[2:3, 1] *A0[1:2]

# L <- L3 / a33
A0[2:3]  = A0[2:3] / A0[2:3, 2]
A0

array([[ 1.        , -0.31816942,  0.        ,  0.        ,  0.        ,
         0.14749359],
       [ 0.        ,  1.        , -0.16756622,  0.        ,  0.        ,
         0.14284152],
       [ 0.        ,  0.        ,  1.        , -0.16344161,  0.        ,
         0.02334625],
       [ 0.        ,  0.        , -0.145825  ,  0.91665   , -0.145825  ,
        -0.1027    ],
       [ 0.        ,  0.        ,  0.        , -0.145825  ,  0.458325  ,
        -0.0675    ]])

In [492]:
# L4 <- L4 -L3 * a33
A0[3:4] = A0[3:4] - A0[3:4,2]* A0[2:3]   #- A0[2:3, 0] *A0[0:1]

# L4 <- L4 / a44
A0[3:4]  = A0[3:4] / A0[3:4, 3]
A0

array([[ 1.        , -0.31816942,  0.        ,  0.        ,  0.        ,
         0.14749359],
       [ 0.        ,  1.        , -0.16756622,  0.        ,  0.        ,
         0.14284152],
       [ 0.        ,  0.        ,  1.        , -0.16344161,  0.        ,
         0.02334625],
       [ 0.        ,  0.        ,  0.        ,  1.        , -0.1633315 ,
        -0.11121611],
       [ 0.        ,  0.        ,  0.        , -0.145825  ,  0.458325  ,
        -0.0675    ]])

In [493]:
# L5 <- L5 -L4 * a44
A0[4:5] =A0[4:5] - A0[4:5,3]* A0[3:4]   #- A0[2:3, 0] *A0[0:1]

# L5 <- L5 / a55
A0[4:5] = A0[4:5] / A0[4:5, 4]

print("Logo, após a eliminação de Gauss a matriz aumentada fica:")
print("\n")
A0

Logo, após a eliminação de Gauss a matriz aumentada fica:




array([[ 1.        , -0.31816942,  0.        ,  0.        ,  0.        ,
         0.14749359],
       [ 0.        ,  1.        , -0.16756622,  0.        ,  0.        ,
         0.14284152],
       [ 0.        ,  0.        ,  1.        , -0.16344161,  0.        ,
         0.02334625],
       [ 0.        ,  0.        ,  0.        ,  1.        , -0.1633315 ,
        -0.11121611],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  1.        ,
        -0.19267366]])

In [494]:
c5 = A0[4:5,5]
c4 = A0[3:4,5] - A0[3:4,4] *c5
c3 = A0[2:3,5] - A0[2:3,3]*c4
c2 = A0[1:2,5] - A0[1:2,5]*c3
c1 = A0[0:1,5] - A0[0:1,1]*c2

C1 = array([c1[0], c2[0], c3[0], c4[0], c5[0] ]).round(4)   #vetor solução para n=0
C1

array([ 0.1929,  0.1428,  0.    , -0.1427, -0.1927])

#### n = 1

In [495]:
#lado direito da equação para n = 1
(dot(subt, C1) + k/2* soma_vet_forca(F,k,1)).round(4)

array([ 0.0667,  0.1892,  0.    , -0.1889, -0.0666])

In [496]:
#aumentada
A0 = array([[ 0.458325, -0.145825,  0.      ,  0.      ,  0.     ,  0.0667],
       [-0.145825,  0.91665 , -0.145825,  0.      ,  0.    ,  0.1892   ],
       [ 0.      , -0.145825,  0.91665 , -0.145825,  0.     , 0.   ],
       [ 0.      ,  0.      , -0.145825,  0.91665 , -0.145825,  -0.1889],
       [ 0.      ,  0.      ,  0.      , -0.145825,  0.458325, -0.0666]])

A0

array([[ 0.458325, -0.145825,  0.      ,  0.      ,  0.      ,  0.0667  ],
       [-0.145825,  0.91665 , -0.145825,  0.      ,  0.      ,  0.1892  ],
       [ 0.      , -0.145825,  0.91665 , -0.145825,  0.      ,  0.      ],
       [ 0.      ,  0.      , -0.145825,  0.91665 , -0.145825, -0.1889  ],
       [ 0.      ,  0.      ,  0.      , -0.145825,  0.458325, -0.0666  ]])

In [497]:
# L1 <- L1 / a11
A0[0:1] = A0[0:1] /  A0[0:1, 0]      #para acessar os elementos [linha:coluna, elemento]

A0

array([[ 1.        , -0.31816942,  0.        ,  0.        ,  0.        ,
         0.14552992],
       [-0.145825  ,  0.91665   , -0.145825  ,  0.        ,  0.        ,
         0.1892    ],
       [ 0.        , -0.145825  ,  0.91665   , -0.145825  ,  0.        ,
         0.        ],
       [ 0.        ,  0.        , -0.145825  ,  0.91665   , -0.145825  ,
        -0.1889    ],
       [ 0.        ,  0.        ,  0.        , -0.145825  ,  0.458325  ,
        -0.0666    ]])

In [498]:
# L2 <- L2 - a21* L1
A0[1:2] = A0[1:2] - A0[1:2, 0] *A0[0:1]
A0[1:2] = A0[1:2] / A0[1:2,1]
A0

array([[ 1.        , -0.31816942,  0.        ,  0.        ,  0.        ,
         0.14552992],
       [ 0.        ,  1.        , -0.16756622,  0.        ,  0.        ,
         0.24179395],
       [ 0.        , -0.145825  ,  0.91665   , -0.145825  ,  0.        ,
         0.        ],
       [ 0.        ,  0.        , -0.145825  ,  0.91665   , -0.145825  ,
        -0.1889    ],
       [ 0.        ,  0.        ,  0.        , -0.145825  ,  0.458325  ,
        -0.0666    ]])

In [499]:
# L3 <- L3 - a31* L1
A0[2:3] = A0[2:3] - A0[2:3, 0] *A0[0:1]

# L3 <- L3 - a32* L2
A0[2:3] = A0[2:3] - A0[2:3, 1] *A0[1:2]

# L <- L3 / a33
A0[2:3]  = A0[2:3] / A0[2:3, 2]
A0

array([[ 1.        , -0.31816942,  0.        ,  0.        ,  0.        ,
         0.14552992],
       [ 0.        ,  1.        , -0.16756622,  0.        ,  0.        ,
         0.24179395],
       [ 0.        ,  0.        ,  1.        , -0.16344161,  0.        ,
         0.03951919],
       [ 0.        ,  0.        , -0.145825  ,  0.91665   , -0.145825  ,
        -0.1889    ],
       [ 0.        ,  0.        ,  0.        , -0.145825  ,  0.458325  ,
        -0.0666    ]])

In [500]:
# L4 <- L4 -L3 * a33
A0[3:4] = A0[3:4] - A0[3:4,2]* A0[2:3]   #- A0[2:3, 0] *A0[0:1]

# L4 <- L4 / a44
A0[3:4]  = A0[3:4] / A0[3:4, 3]
A0

array([[ 1.        , -0.31816942,  0.        ,  0.        ,  0.        ,
         0.14552992],
       [ 0.        ,  1.        , -0.16756622,  0.        ,  0.        ,
         0.24179395],
       [ 0.        ,  0.        ,  1.        , -0.16344161,  0.        ,
         0.03951919],
       [ 0.        ,  0.        ,  0.        ,  1.        , -0.1633315 ,
        -0.20512299],
       [ 0.        ,  0.        ,  0.        , -0.145825  ,  0.458325  ,
        -0.0666    ]])

In [501]:
# L5 <- L5 -L4 * a44
A0[4:5] =A0[4:5] - A0[4:5,3]* A0[3:4]   #- A0[2:3, 0] *A0[0:1]

# L5 <- L5 / a55
A0[4:5] = A0[4:5] / A0[4:5, 4]

print("Logo, após a eliminação de Gauss a matriz aumentada fica:")
print("\n")
A0

Logo, após a eliminação de Gauss a matriz aumentada fica:




array([[ 1.        , -0.31816942,  0.        ,  0.        ,  0.        ,
         0.14552992],
       [ 0.        ,  1.        , -0.16756622,  0.        ,  0.        ,
         0.24179395],
       [ 0.        ,  0.        ,  1.        , -0.16344161,  0.        ,
         0.03951919],
       [ 0.        ,  0.        ,  0.        ,  1.        , -0.1633315 ,
        -0.20512299],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  1.        ,
        -0.22211845]])

In [502]:
c5 = A0[4:5,5]
c4 = A0[3:4,5] - A0[3:4,4] *c5
c3 = A0[2:3,5] - A0[2:3,3]*c4
c2 = A0[1:2,5] - A0[1:2,5]*c3
c1 = A0[0:1,5] - A0[0:1,1]*c2

C2 = array([c1[0], c2[0], c3[0], c4[0], c5[0] ]).round(3)
C2

array([ 0.222,  0.242,  0.   , -0.241, -0.222])

### Erro absoluto

In [503]:
x = linspace(2,4, 5)
t1 = 0.25
u = 1/pi**2 * sin(pi * x)  * exp(- t1)

In [508]:
def erro(a,b):
  E = abs(a-b)
  return E
E = []
for i in range( len(x)):
  E.append(  erro(C2[i], u[i]))

E = array(E)
E

array([2.22000000e-01, 1.63090983e-01, 2.89907026e-17, 1.62090983e-01,
       2.22000000e-01])

In [513]:
dot(E.T, E) * h

np.float64(0.07572007770010511)

In [514]:
#norma discreta do erro
h = abs(x[1] - x[2])
def norma_discreta(E,h):
  N = sqrt(h * dot(E.T, E) )
  return N

norma_discreta(E,h)

np.float64(0.27517281424607537)