<a href="https://colab.research.google.com/github/MukRodrigues/Projetos-Python/blob/main/Calculo_Sistema.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [70]:
import numpy as mp
from numpy import *
from numpy.linalg import *

In [88]:
A = array([[0.1667, 0.0833, 0      , 0      , 0 ],
[0.0833 , 0.3334 , 0.0833 , 0      , 0 ],
[0      , 0.0833 , 0.3334 , 0.0833 , 0],
[0      , 0      , 0.0833 , 0.3334 , 0.0833],
[0      , 0      , 0      , 0.0833 , 0.1667 ]])

B = array([[2.333 , -1.833 , 0      , 0      , 0  ],
[-1.833 , 4.666 , -1.833 , 0      , 0  ],
[0      , -1.833 , 4.666 , -1.833 , 0],
[0      , 0      , -1.833 , 4.666 , -1.833],
[0      , 0      , 0      , -1.833 , 2.333 ]])

F = array([0.1259, 0.4489,0, -0.4484, -0.1257 ])

c0 = array([0, 0.101321, 0, -0.101321, 0])

def soma_vet_forca(F,k,n):
  soma = (exp( (n+1)*k   ) + exp( (n)*k))   #F = F_{n+1} + F_{n}
  return F*soma

In [91]:
soma_vet_forca(F,k,0)

array([ 0.2875588 ,  1.02529901,  0.        , -1.024157  , -0.28710199])

Operações

$$\left(A+ \frac{k}{2} B \right) c_{n+1} = \left(A- \frac{k}{2} B \right)c_{n} + \frac{k}{2}(F_{n+1} + F_{n} ) $$

In [93]:
k = 0.25
soma = A + k/2 * B
soma

array([[ 0.458325, -0.145825,  0.      ,  0.      ,  0.      ],
       [-0.145825,  0.91665 , -0.145825,  0.      ,  0.      ],
       [ 0.      , -0.145825,  0.91665 , -0.145825,  0.      ],
       [ 0.      ,  0.      , -0.145825,  0.91665 , -0.145825],
       [ 0.      ,  0.      ,  0.      , -0.145825,  0.458325]])

In [95]:
subt = A - k/2 * B
subt

array([[-0.124925,  0.312425,  0.      ,  0.      ,  0.      ],
       [ 0.312425, -0.24985 ,  0.312425,  0.      ,  0.      ],
       [ 0.      ,  0.312425, -0.24985 ,  0.312425,  0.      ],
       [ 0.      ,  0.      ,  0.312425, -0.24985 ,  0.312425],
       [ 0.      ,  0.      ,  0.      ,  0.312425, -0.124925]])

In [102]:
#lado direito da equação:
(dot(dot(inv(soma), subt), c0) + k/2* dot(dot(inv(soma), subt), soma_vet_forca(F,k,0))).round(3)

array([ 0.138, -0.028,  0.   ,  0.028, -0.138])

In [84]:
#calculando c_1 a partir de c0
def sol_sistema(n):
  c = dot(dot(inv(soma), subt), c0) + k/2* dot(dot(inv(soma), subt), soma_vet_forca(F,k,n))
  return c

c1 = sol_sistema(0).round(3)
c1

array([ 0.138, -0.028,  0.   ,  0.028, -0.138])

In [83]:
#calculando c_2 a partir de c1
def sol_sistema(n):
  c = dot(dot(inv(soma), subt), c1) + k/2* dot(dot(inv(soma), subt), soma_vet_forca(F,k,n))
  return c

c2 = sol_sistema(1).round(4)
c2

array([ 0.0536,  0.0341,  0.0001, -0.034 , -0.0535])