<a href="https://colab.research.google.com/github/MukRodrigues/Projetos-Python/blob/main/Vetor_For%C3%A7a_Local.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Vetor Força Local

In [1]:
import numpy as np

In [2]:
# ctes
h = 0.5
C = 2 + np.pi**2 / 4

# pesos
phi1_xi1 = (1+np.sqrt(3)/3 )/2 # aprox. 0.788
phi1_xi2 =(1-np.sqrt(3)/3 )/2  # aprox. 0.211

phi2_xi1 = (1-np.sqrt(3)/3 )/2
phi2_xi2 = (1+np.sqrt(3)/3 )/2

def Fe(x1, x2):

    # pontos de Gauss  / npg
    xg1 = x1 * phi1_xi1 + x2 * phi1_xi2
    xg2 = x1 * phi1_xi2 + x2 * phi1_xi1

    # calcular f
    f1 = C * np.sin(np.pi/2 * xg1)
    f2 = C * np.sin(np.pi/2 * xg2)

    # elementos do vetor força local F_a, a=1 , 2
    F1 = h/2 * (f1 * phi1_xi1 + f2 * phi1_xi2)
    F2 = h/2 * (f1 * phi2_xi1 + f2 * phi2_xi2)

    return np.array([F1, F2])

Cálculo das componetentes para cada elemento $e=1, 2, 3, 4$.

In [3]:
# e = 1
np.round(Fe(2,2.5),3)

array([-0.283, -0.55 ])

In [4]:
# e = 2
np.round(Fe(2.5,3),3)

array([-0.95 , -1.061])

In [5]:
# e = 3
np.round(Fe(3,3.5),3)

array([-1.061, -0.95 ])

In [6]:
# e = 4
np.round(Fe(3.5,4),3)

array([-0.55 , -0.283])

In [7]:
x = np.linspace(2, 4, 5)
x

array([2. , 2.5, 3. , 3.5, 4. ])

In [8]:
for i in range( len(x)-1):
  print(np.round(Fe(x[i], x[i+1]),3))

[-0.283 -0.55 ]
[-0.95  -1.061]
[-1.061 -0.95 ]
[-0.55  -0.283]


In [9]:
-0.55-0.95

-1.5

In [10]:
-1.061*2

-2.122

In [11]:
-0.95-0.55

-1.5