<a href="https://colab.research.google.com/github/MukRodrigues/Projetos-Python/blob/main/Vetor_For%C3%A7a_Local.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Vetor Força Local

## Caso 1D Estacionário

In [10]:
import numpy as np

In [11]:
# ctes
h = 0.5
C = 2 + np.pi**2 / 4

# pesos
phi1_xi1 = (1+np.sqrt(3)/3 )/2 # aprox. 0.788
phi1_xi2 =(1-np.sqrt(3)/3 )/2  # aprox. 0.211

phi2_xi1 = (1-np.sqrt(3)/3 )/2
phi2_xi2 = (1+np.sqrt(3)/3 )/2

def Fe(x1, x2):

    # pontos de Gauss  / npg
    xg1 = x1 * phi1_xi1 + x2 * phi1_xi2
    xg2 = x1 * phi1_xi2 + x2 * phi1_xi1

    # calcular f
    f1 = C * np.sin(np.pi/2 * xg1)
    f2 = C * np.sin(np.pi/2 * xg2)

    # elementos do vetor força local F_a, a=1 , 2
    F1 = h/2 * (f1 * phi1_xi1 + f2 * phi1_xi2)
    F2 = h/2 * (f1 * phi2_xi1 + f2 * phi2_xi2)

    return np.array([F1, F2])

Cálculo das componetentes para cada elemento $e=1, 2, 3, 4$.

In [12]:
# e = 1
np.round(Fe(2,2.5),3)

array([-0.283, -0.55 ])

In [13]:
# e = 2
np.round(Fe(2.5,3),3)

array([-0.95 , -1.061])

In [14]:
# e = 3
np.round(Fe(3,3.5),3)

array([-1.061, -0.95 ])

In [15]:
# e = 4
np.round(Fe(3.5,4),3)

array([-0.55 , -0.283])

In [16]:
x = np.linspace(2, 4, 5)
x

array([2. , 2.5, 3. , 3.5, 4. ])

In [17]:
for i in range( len(x)-1):
  print(np.round(Fe(x[i], x[i+1]),3))

[-0.283 -0.55 ]
[-0.95  -1.061]
[-1.061 -0.95 ]
[-0.55  -0.283]


In [18]:
-0.55-0.95

-1.5

In [19]:
-1.061*2

-2.122

In [20]:
-0.95-0.55

-1.5

## Caso 1D Transiente

In [21]:
import numpy as np

In [22]:
# Constantes do problema
h = 0.5
C = 1 + 1/np.pi**2

# Pontos de Gauss
xi1 = -np.sqrt(3)/3
xi2 =  np.sqrt(3)/3

# Funções de forma avaliadas nos pontos de Gauss
phi1_xi1 = (1 - xi1)/2
phi1_xi2 = (1 - xi2)/2

phi2_xi1 = (1 + xi1)/2
phi2_xi2 = (1 + xi2)/2


def Fe_t(x1, x2, t):
    """
    Calcula o vetor força local do elemento [x1,x2]
    no instante t.
    """

    # Pontos físicos de Gauss
    xg1 = x1*phi1_xi1 + x2*phi1_xi2
    xg2 = x1*phi1_xi2 + x2*phi1_xi1

    # Avaliação de f(x,t)
    f1 = C*np.sin(np.pi*xg1)*np.exp(-t)
    f2 = C*np.sin(np.pi*xg2)*np.exp(-t)

    # Componentes do vetor força local
    F1 = h/2*(f1*phi1_xi1 + f2*phi1_xi2)
    F2 = h/2*(f1*phi2_xi1 + f2*phi2_xi2)

    return np.array([F1, F2])

In [23]:
t = 0.25   # valor dado no trabalho

elementos = [
    (2.0, 2.5),
    (2.5, 3.0),
    (3.0, 3.5),
    (3.5, 4.0)
]

for i, (x1, x2) in enumerate(elementos, start=1):
    print(f"F^{i} =")
    print(Fe_t(x1, x2, t))
    print()

F^1 =
[0.09795182 0.17464868]

F^2 =
[0.17464868 0.09795182]

F^3 =
[-0.09795182 -0.17464868]

F^4 =
[-0.17464868 -0.09795182]

